openapi: 3.0.3

info:
  title: Ozi
  version: 0.1.0
  description: Управление рассылками.
  x-config:
    schema:
      type: object
      properties:
        token:
          type: string
          description: Токен аутинтификации
      required:
        - token

components:
  schemas:
    Client:
      type: object
      properties:
        config:
          $ref: "https://api.tomoru.ru/openapi#/components/schemas/TomoruConfig"
        botId:
          $ref: "https://api.tomoru.ru/openapi#/components/schemas/botId"
        chatId:
          $ref: "https://api.tomoru.ru/openapi#/components/schemas/chatId"
      required:
        - config
        - botId
        - chatId
    MailingID:
      type: integer
      description: Идентификатор рассылки
    Detail:
      type: object
      properties:
        detail:
          type: string
          description: Подробности
      required:
        - detail
    Error:
      type: object
      properties:
        error:
          type: string
          description: Ошибка
      required:
        - error

  responses:
    TokenError:
      description: Неверный токен аутинтификации
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Detail"
    UnknownError:
      description: Что-то пошло не так
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

paths:
  /mailings:
    post:
      operationId: listMailings
      summary: Получить список рассылок
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                config:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/TomoruConfig"
              required:
                - config
      responses:
        200:
          description: Рассылки
          content:
            application/json:
              schema:
                type: object
                properties:
                  mailings:
                    type: string
                    description: Список рассылок
                required:
                  - mailings
        204:
          description: Нет доступных рассылок
        403:
          $ref: "#/components/responses/TokenError"
        500:
          $ref: "#/components/responses/UnknownError"

  /subscriptions:
    post:
      operationId: listClientSubscriptions
      summary: Получить подписки клиента
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Client"
      responses:
        200:
          description: Рассылки
          content:
            application/json:
              schema:
                type: object
                properties:
                  mailings:
                    type: string
                    description: Список рассылок
                required:
                  - mailings
        204:
          description: Нет подписок
        403:
          $ref: "#/components/responses/TokenError"
        500:
          $ref: "#/components/responses/UnknownError"

  /subscribe:
    post:
      operationId: subscribeClient
      summary: Подписать клиента на рассылку
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Client"
                - $ref: "#/components/schemas/MailingID"
      responses:
        204:
          description: Клиент успешно подписан
        403:
          $ref: "#/components/responses/TokenError"
        404:
          description: Рассылка не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Detail"
        409:
          description: Клиент уже подписан
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Detail"
        500:
          $ref: "#/components/responses/UnknownError"

  /unsubscribe:
    post:
      operationId: unsubscribeClient
      summary: Отписать клиента от рассылки
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Client"
                - $ref: "#/components/schemas/MailingID"
      responses:
        204:
          description: Клиент успешно отписан
        403:
          $ref: "#/components/responses/TokenError"
        404:
          description: Рассылка не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Detail"
        409:
          description: Клиент не подписан
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Detail"
        500:
          $ref: "#/components/responses/UnknownError"
