openapi: 3.0.3

info:
  title: Ozi
  version: 0.1.0
  description: Управление рассылками.
  x-config:
    schema:
      type: object
      properties:
        token:
          type: string
          description: Токен аутинтификации
      required:
        - token

servers:
  - url: https://tomoru-mailings.herokuapp.com/api

components:
  schemas:
    Client:
      type: object
      properties:
        config:
          $ref: "https://api.tomoru.ru/openapi#/components/schemas/TomoruConfig"
        botId:
          $ref: "https://api.tomoru.ru/openapi#/components/schemas/botId"
        chatId:
          $ref: "https://api.tomoru.ru/openapi#/components/schemas/chatId"
      required:
        - config
        - botId
        - chatId
    MailingID:
      type: integer
      description: Идентификатор рассылки
    Detail:
      type: object
      properties:
        detail:
          type: string
          description: Подробности
      required:
        - detail
    Error:
      type: object
      properties:
        error:
          type: string
          description: Ошибка
      required:
        - error

  responses:
    TokenError:
      description: Неверный токен аутинтификации
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Detail"
    UnknownError:
      description: Что-то пошло не так
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

paths:
  /mailings:
    post:
      operationId: listMailings
      summary: Получить список рассылок
      tags:
        - tomoru/call
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                config:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/TomoruConfig"
              required:
                - config
      responses:
        200:
          description: Рассылки
          content:
            application/json:
              schema:
                type: object
                properties:
                  mailings:
                    type: string
                    description: Список рассылок
                required:
                  - mailings
        204:
          description: Нет доступных рассылок
        403:
          $ref: "#/components/responses/TokenError"
        500:
          $ref: "#/components/responses/UnknownError"

  /subscriptions:
    post:
      operationId: listClientSubscriptions
      summary: Получить подписки клиента
      tags:
        - tomoru/call
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Client"
      responses:
        200:
          description: Рассылки
          content:
            application/json:
              schema:
                type: object
                properties:
                  mailings:
                    type: string
                    description: Список рассылок
                required:
                  - mailings
        204:
          description: Нет подписок
        403:
          $ref: "#/components/responses/TokenError"
        500:
          $ref: "#/components/responses/UnknownError"

  /subscribe:
    post:
      operationId: subscribeClient
      summary: Подписать клиента на рассылку
      tags:
        - tomoru/call
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                config:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/TomoruConfig"
                botId:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/botId"
                chatId:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/chatId"
                mailingId:
                  $ref: "#/components/schemas/MailingID"
              required:
                - config
                - botId
                - chatId
                - mailingId
      responses:
        204:
          description: Клиент успешно подписан
        403:
          $ref: "#/components/responses/TokenError"
        404:
          description: Рассылка не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Detail"
        409:
          description: Клиент уже подписан
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Detail"
        500:
          $ref: "#/components/responses/UnknownError"

  /unsubscribe:
    post:
      operationId: unsubscribeClient
      summary: Отписать клиента от рассылки
      tags:
        - tomoru/call
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                config:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/TomoruConfig"
                botId:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/botId"
                chatId:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/chatId"
                mailingId:
                  $ref: "#/components/schemas/MailingID"
              required:
                - config
                - botId
                - chatId
                - mailingId
      responses:
        204:
          description: Клиент успешно отписан
        403:
          $ref: "#/components/responses/TokenError"
        404:
          description: Рассылка не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Detail"
        409:
          description: Клиент не подписан
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Detail"
        500:
          $ref: "#/components/responses/UnknownError"

  /find-mailing:
    post:
      operationId: findMailing
      summary: Найти рассылку
      description: Поиск рассылки по неточному названию; названию, которое может содержать незначительные опечатки.
      tags:
        - tomoru/call
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                config:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/TomoruConfig"
                name:
                  type: string
                  description: Название
              required:
                - config
                - name
      responses:
        200:
          description: Рассылка найдена
          content:
            application/json:
              schema:
                type: object
                properties:
                  mailingId:
                    $ref: "#/components/schemas/MailingID"
                required:
                  - mailingId
        403:
          $ref: "#/components/responses/TokenError"
        404:
          description: Рассылка не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Detail"
        500:
          $ref: "#/components/responses/UnknownError"

  /plan-update:
    post:
      operationId: planUpdate
      summary: Запланировать обновление
      description: Запланировать отправку обновления рассылки для клиента через некоторое время.
      tags:
        - tomoru/call
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                config:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/TomoruConfig"
                botId:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/botId"
                chatId:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/chatId"
                mailingId:
                  $ref: "#/components/schemas/MailingID"
                hours:
                  type: integer
                  description: Часы
                minutes:
                  type: integer
                  description: Минуты
              required:
                - config
                - botId
                - chatId
                - mailingId
      responses:
        202:
          description: Обновление запланировано
        403:
          $ref: "#/components/responses/TokenError"
        404:
          description: Рассылка не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Detail"
        500:
          $ref: "#/components/responses/UnknownError"

  /schedule-update:
    post:
      operationId: scheduleUpdate
      summary: Установить обновление по расписанию
      description: Установить отправку обновения рассылки для клиента, начиная с определенного момента (дата и время). Обновление будет повторяться с заданным периодом.
      tags:
        - tomoru/call
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                config:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/TomoruConfig"
                botId:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/botId"
                chatId:
                  $ref: "https://api.tomoru.ru/openapi#/components/schemas/chatId"
                mailingId:
                  $ref: "#/components/schemas/MailingID"
                time:
                  type: string
                  format: date-time
                  description: Время (UTC)
                date:
                  type: string
                  format: time
                  description: Дата (UTC)
                repeat:
                  type: integer
                  description: Период в минутах
              required:
                - config
                - botId
                - chatId
                - mailingId
      responses:
        202:
          description: Обновление установлено
        403:
          $ref: "#/components/responses/TokenError"
        404:
          description: Рассылка не найдена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Detail"
        500:
          $ref: "#/components/responses/UnknownError"

  /create-hook:
    post:
      operationId: subscribeOnUpdates
      summary: Подписаться на обновления рассылок
      tags:
        - tomoru/subscribe
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tomoruCallbackUrl:
                  type: string
              required:
                - tomoruCallbackUrl
      callbacks:
        newUpdate:
          "{$request.body#/tomoruCallbackUrl}":
            post:
              summary: Новое обновление
              description: Новое обновление рассылки.
              requestBody:
                content:
                  application/json:
                    schema:
                      allOf:
                        - $ref: "https://api.tomoru.ru/openapi#/components/schemas/TomoruEvent"
                        - type: object
                          properties:
                            data:
                              type: object
                              properties:
                                mailing:
                                  type: string
                                  description: Название рассылки
                              required:
                                - mailing
              responses:
                200:
                  description: Обновление получено
                500:
                  $ref: "#/components/responses/UnknownError"
      responses:
        201:
          description: Подписка оформлена
        500:
          $ref: "#/components/responses/UnknownError"
