# Generated by Django 3.1 on 2020-09-07 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('background_task', '0002_auto_20170927_1109'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot', models.CharField(max_length=50)),
                ('chat', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Hook',
                'verbose_name_plural': 'Hooks',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('common', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('repeat', models.CharField(blank=True, max_length=25, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ozi.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozi.mailing')),
                ('task', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='background_task.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Update',
                'verbose_name_plural': 'Updates',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='subscriptions',
            field=models.ManyToManyField(to='ozi.Mailing'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('bot', 'chat')},
        ),
    ]
