# Generated by Django 3.1 on 2020-09-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hook',
            name='target',
            field=models.URLField(max_length=500),
        ),
    ]
