# Generated by Django 3.1 on 2020-09-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozi', '0002_auto_20200905_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='common',
            field=models.BooleanField(default=True),
        ),
    ]
