# Generated by Django 3.1.1 on 2020-09-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozi', '0002_auto_20200909_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='ozi.Mailing'),
        ),
    ]
