# Generated by Django 3.1 on 2020-09-01 00:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ozi', '0004_auto_20200901_0013'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mailing',
            unique_together={('user', 'name')},
        ),
    ]
