# Generated by Django 3.1 on 2020-09-02 01:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0002_auto_20170927_1109'),
        ('ozi', '0005_auto_20200901_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Mailing', 'verbose_name_plural': 'Mailings'},
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozi.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozi.mailing')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background_task.task')),
            ],
            options={
                'verbose_name': 'Update',
                'verbose_name_plural': 'Updates',
            },
        ),
    ]
