# Generated by Django 3.1 on 2020-09-02 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0002_auto_20170927_1109'),
        ('ozi', '0006_auto_20200902_0102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updates',
            new_name='Update',
        ),
    ]
