# Generated by Django 3.1 on 2020-09-02 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ozi', '0007_auto_20200902_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ozi.client'),
        ),
    ]
