# Generated by Django 3.1 on 2020-09-02 08:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0002_auto_20170927_1109'),
        ('ozi', '0010_auto_20200902_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='update',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='update',
            name='task',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='background_task.task'),
        ),
    ]
