# Generated by Django 3.1 on 2020-09-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozi', '0012_update_repeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.URLField()),
            ],
            options={
                'verbose_name': 'Hook',
                'verbose_name_plural': 'Hooks',
            },
        ),
    ]
