# Generated by Django 3.1 on 2020-09-04 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0002_auto_20170927_1109'),
        ('ozi', '0014_auto_20200904_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='task',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='background_task.task'),
        ),
    ]
